import 'package:chat_app_ui/constants/images_names.dart';
import 'package:chat_app_ui/constants/message_list.dart';
import 'package:chat_app_ui/screens/home_screen/components/members_list.dart';

final List<UserList> userList = [
  UserList(
    name: "Aarav Dosth",
    lastMessage: conversation1.last.message,
    unreadMessageCount: 1,
    isOnline: true,
    lastTime: '15 min',
    isSentByU: conversation1.last.sendByU,
    imgName: imageNames.firstprofile,
    listChat: conversation1,
  ),
  UserList(
    name: "Ishaan",
    lastMessage: conversation2.last.message,
    unreadMessageCount: 0,
    isOnline: false,
    isSentByU: conversation2.last.sendByU,
    isSeenByOther: true,
    lastTime: '32 min',
    imgName: imageNames.secondprofile,
    listChat: conversation2,
  ),
  UserList(
    name: "Reyansh",
    lastMessage: conversation3.last.message,
    unreadMessageCount: 10,
    isOnline: true,
    lastTime: '49 min',
    imgName: imageNames.thridProfile,
    listChat: conversation3,
    isSentByU: conversation3.last.sendByU,
  ),
  UserList(
    name: "Arjun",
    lastMessage: conversation4.last.message,
    unreadMessageCount: 0,
    isOnline: false,
    isSentByU: conversation4.last.sendByU,
    isSeenByOther: false,
    lastTime: '01/12/2024',
    imgName: imageNames.fourthProfile,
    listChat: conversation4,
  ),
  UserList(
    name: "Kabir",
    lastMessage: conversation5.last.message,
    unreadMessageCount: 0,
    isOnline: true,
    isSentByU: conversation5.last.sendByU,
    isSeenByOther: false,
    lastTime: '04/12/2024',
    imgName: imageNames.fivefthProfile,
    listChat: conversation5,
  ),
  UserList(
    name: "Bheem",
    lastMessage: conversation6.last.message,
    unreadMessageCount: 1,
    isOnline: true,
    isSentByU: conversation6.last.sendByU,
    lastTime: '30/12/2024',
    imgName: imageNames.sixProfile,
    listChat: conversation6,
  ),
];
